---
- name: Create user
  ansible.builtin.user:
    name: "{{ camper.username }}"
    comment: "{{ camper.first_name }} {{ camper.last_name }} ({{ camper.email }})"
    home: "{{ camper.home }}"
    password: "{{ camper_password | password_hash('sha512') }}"
    groups:
      - campers
    state: present

- name: Check if placeholder file exists
  register: r_ph_stat
  become: false
  vars:
    ansible_user: "{{ camper.username }}"
    ansible_password: "{{ camper_password }}"
  ansible.builtin.stat:
    path: "{{ camper.home }}/placeholder.txt"

- name: Create a placeholder file of random size
  when:
    - not (r_ph_stat.stat.exists | default(false))
    - camper.size_mb
  become: false
  vars:
    ansible_user: "{{ camper.username }}"
    ansible_password: "{{ camper_password }}"
  ansible.builtin.command:
    cmd: "fallocate -l {{ camper.size_mb }}M {{ camper.home }}/placeholder.txt"
