---
- name: Generate Let's Encrypt account key
  community.crypto.openssl_privatekey:
    path: "{{ acme_letsencrypt_account_key }}"

- name: Generate Let's Encrypt private key
  community.crypto.openssl_privatekey:
    path: "{{ acme_letsencrypt_keys_dir }}/{{ acme_domain_name }}.key"

- name: Generate Let's Encrypt CSR
  community.crypto.openssl_csr:
    path: "{{ acme_letsencrypt_csrs_dir }}/{{ acme_domain_name }}.csr"
    privatekey_path: "{{ acme_letsencrypt_keys_dir }}/{{ acme_domain_name }}.key"
    common_name: "{{ acme_domain_name }}"

- name: Begin Let's Encrypt challenges
  register: r_acme_challenge
  community.crypto.acme_certificate:
    acme_directory: "{{ acme_directory }}"
    acme_version: "{{ acme_version }}"
    account_key_src: "{{ acme_letsencrypt_account_key }}"
    account_email: "{{ acme_email }}"
    terms_agreed: true
    challenge: "{{ acme_challenge_type }}"
    csr: "{{ acme_letsencrypt_csrs_dir }}/{{ acme_domain_name }}.csr"
    dest: "{{ acme_letsencrypt_certs_dir }}/{{ acme_domain_name }}.pem"
    fullchain_dest: "{{ acme_letsencrypt_certs_dir }}/fullchain_{{ acme_domain_name }}.pem"
    remaining_days: 91

- name: Create .well-known/acme-challenge directory
  ansible.builtin.file:
    path: /var/www/html/.well-known/acme-challenge
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Implement http-01 challenge files
  ansible.builtin.copy:
    content: "{{ r_acme_challenge['challenge_data'][acme_domain_name]['http-01']['resource_value'] }}"
    dest: /var/www/html/{{ r_acme_challenge['challenge_data'][acme_domain_name]['http-01']['resource'] }}
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Complete Let's Encrypt challenges
  notify: Restart nginx
  community.crypto.acme_certificate:
    acme_directory: "{{ acme_directory }}"
    acme_version: "{{ acme_version }}"
    account_key_src: "{{ acme_letsencrypt_account_key }}"
    account_email: "{{ acme_email }}"
    challenge: "{{ acme_challenge_type }}"
    csr: "{{ acme_letsencrypt_csrs_dir }}/{{ acme_domain_name }}.csr"
    dest: "{{ acme_letsencrypt_certs_dir }}/{{ acme_domain_name }}.pem"
    chain_dest: "{{ acme_letsencrypt_certs_dir }}/chain_{{ acme_domain_name }}.pem"
    fullchain_dest: "{{ acme_letsencrypt_certs_dir }}/fullchain_{{ acme_domain_name }}.pem"
    data: "{{ r_acme_challenge }}"

- name: Template nginx site conf
  notify: Restart nginx
  ansible.builtin.template:
    src: site-ssl.conf.j2
    dest: /etc/nginx/sites-available/{{ acme_domain_name }}.conf
    owner: root
    group: root
    mode: "0664"
