---
- name: Setup Expand Disk Space Demo
  hosts: localhost
  gather_facts: false
  become: false

  vars_files:
    - vars/aws.yml

  ## Required ENV vars ##
  # DT_API_TOKEN

  tasks:
    - name: Include platform variables
      ansible.builtin.include_vars:
        file: "vars/{{ target_platform }}_launch_template.yml"

    - name: Setup AWS environment
      ansible.builtin.include_tasks:
        file: tasks/aws.yml
...
