---
- name: Demonstration "Hello World" playbook
  hosts: localhost
  gather_facts: false
  become: false

  tasks:
    - name: Say hello
      ansible.builtin.debug:
        msg: "Hello {{ audience | default('world') }}!"
