---
- hosts: "{{ _hosts | default(omit) }}"
  name: Setup systemd and nginx site on host
  become: true

  vars:
    site_root: /usr/share/nginx/demo

  tasks:
    - name: Unarchive a file that needs to be downloaded (added in 2.0)
      ansible.builtin.unarchive:
        src: https://artifacts.autodotes.com/demo-site.tar.gz
        dest: "{{ site_root | dirname }}"
        remote_src: true
        validate_certs: false

    - name: Enable nginx
      ansible.builtin.systemd_service:
        name: nginx
        state: restarted
        enabled: true

    - name: Setup unit files
      ansible.builtin.include_role:
        name: systemd_nginx
      vars:
        systemd_nginx_path_modified: "{{ site_root }}"
        systemd_nginx_eda_webhook: http://192.168.0.108:5003/endpoint
