---
- name: Manage proxmox kvm(s) state
  hosts: localhost
  gather_facts: false
  become: false

  # Example
  # vars:
  #   proxmox_instances:
  #     - node: pve
  #       name: mgmt
  #       state: started

  tasks:
    - name: Assert kvms defined
      ansible.builtin.assert:
        that: proxmox_kvms is defined

    - name: Manage kvm state
      loop: "{{ proxmox_kvms }}"
      loop_control:
        loop_var: kvm
        label: "{{ kvm.name }}@{{ kvm.node }}"
      community.general.proxmox_kvm:
        node: "{{ kvm.node }}"
        name: "{{ kvm.name }}"
        state: "{{ kvm.state }}"
        api_token_id: "{{ proxmox_api_token_id }}"
        api_token_secret: "{{ proxmox_api_token_secret }}"
