---
- name: Login random sample of users
  hosts: camp
  gather_facts: false

  vars_files:
    - vars/camper_creds.yml
    - vars/campers.yml

  tasks:
    - name: Ensure camp is open
      block:
        - name: Check if camp is open
          ansible.builtin.wait_for_connection:
          timeout: 30
      rescue:
        - name: Gracefully bail out if camp is closed
          ansible.builtin.meta: end_play

    - name: Login users
      loop: "{{ campers | random_sample(size=3) }}"
      loop_control:
        loop_var: camper
        label: "{{ camper.username }}"
      vars:
        ansible_user: "{{ camper.username }}"
        ansible_password: "{{ camper_password }}"
      ansible.builtin.stat:
        path: "{{ camper.home }}"
