---
- name: Pre-process patch targets and dispatch jobs
  hosts: "{{ patch_targets | default(omit) }}"
  become: true

  tasks:
    - name: Identify DNF changes
      check_mode: true
      ansible.builtin.dnf:
        name: '*'
        state: latest
        update_cache: true

    - name: DEBUG
      ansible.builtin.debug:
        msg: "{{ hostvars[inventory_hostname]['ansible_facts'] }}"

    - name: Check service status
      ansible.builtin.service_facts:

    - name: Group by operating system
      delegate_to: localhost
      run_once: true
      ansible.builtin.set_fact:
        dispatch_groups: "{{ hostvars | group_by_path }}"
