---
- name: Pre-process patch targets and dispatch jobs
  hosts: "{{ patch_targets.keys() | default(omit) }}"
  become: true

  tasks:
    - name: Identify DNF changes
      check_mode: true
      ansible.builtin.dnf:
        name: '*'
        state: latest
        update_cache: true

    - name: Check service status
      ansible.builtin.service_facts:

- name: Dispatch schedules for downstream workflow
  hosts: "{{ patch_targets.keys() | default(omit) }}"
  become: false
  gather_facts: false

  vars:
    # for testing, override with survey
    # change_request: CHG01234 # source from ingress (itsm)
    change_request_group: Ansible West Tigers
    change_task_owner: zleblanc
    change_window_timezone: "{{ patch_targets[inventory_hostname]['change_window_timezone'] | default('America/Chicago') }}" # America/Chicago
    change_window_datetime: "{{ patch_targets[inventory_hostname]['change_window_datetime'] }}" # "2025-04-11 11:10:00"
    # for reporting
    # report_server: some_host_in_inventory
    # report_web_directory: /var/www/html

  tasks:
    - name: Create change request
      tags: snow
      register: r_chg_req
      delegate_to: localhost
      run_once: true
      servicenow.itsm.change_request:
        type: standard
        state: new
        requested_by: zleblanc
        short_description: Batch Application Upgrade
        description: "Affected hosts: {{ ','.join(ansible_play_hosts) }}"
        category: system_software
        priority: moderate
        risk: low
        impact: low

    - name: Update change request status
      tags: snow
      delegate_to: localhost
      run_once: true
      servicenow.itsm.change_request:
        number: "{{ r_chg_req.record.number }}"
        state: scheduled
        assignment_group: "{{ change_request_group }}"

    - name: Update change request status
      tags: snow
      delegate_to: localhost
      run_once: true
      servicenow.itsm.change_request:
        number: "{{ r_chg_req.record.number }}"
        state: implement

    - name: Create a change task
      tags: snow
      delegate_to: localhost
      register: r_chg_task
      servicenow.itsm.change_request_task:
        # configuration_item: "{{ inventory_hostname }}"
        change_request_number: "{{ r_chg_req.record.number }}"
        type: implementation
        state: open
        assigned_to: "{{ change_task_owner }}"
        short_description: "patching {{ inventory_hostname }}"
        description: "starting patch @ {{ change_window_datetime }} {{ change_window_timezone }}"
        planned_start_date: "{{ change_window_datetime }} {{ change_window_timezone }}"
        other:
          approval: approved

    - name: Create report base
      tags: [reporting]
      delegate_to: "{{ report_server }}"
      run_once: true
      become: true
      vars:
        change_request: "{{ r_chg_req.record.number }}"
      ansible.builtin.template:
        src: templates/report.html.j2
        dest: "{{ report_web_directory }}/{{ r_chg_req.record.number }}.html"
        owner: root
        group: root
        mode: "0644"

    - name: Create job status base
      tags: [reporting]
      delegate_to: "{{ report_server }}"
      run_once: true
      become: true
      ansible.builtin.template:
        src: templates/jobs.csv.j2
        dest: "{{ report_web_directory }}/jobs/{{ r_chg_req.record.number }}.csv"
        owner: root
        group: root
        mode: "0644"

    - name: Get current datetime
      ansible.builtin.set_fact:
        current_datetime: "{{ lookup('pipe', 'TZ=\"' + change_window_timezone + '\" date \"+%Y-%m-%d %H:%M:%S\"') }}"

    - name: Assert valid date time for change window
      ansible.builtin.assert:
        that: (change_window_datetime|to_datetime - current_datetime|to_datetime).total_seconds() > 0
        fail_msg: Please ensure that provided date time is in the future

    - name: Prep host metadata
      ansible.builtin.set_fact:
        # Path determination (simple example)
        dispatch_workflow: "rhel{{ ansible_distribution_version.replace('.', '_') }}"
        dispatch_host_metadata:
          _hosts: "{{ inventory_hostname }}"
          version: "{{ ansible_distribution_version }}"
          kernel: "{{ ansible_kernel }}"
          arch: "{{ ansible_architecture  }}"
          change_request: "{{ r_chg_req.record.number }}"
          change_request_task: "{{ r_chg_task.record.number }}"
          change_window_timezone: "{{ change_window_timezone }}"
          change_window_datetime: "{{ change_window_datetime }}"

    - name: Prep other metadata
      ansible.builtin.set_fact:
        dispatch_other_data:
          report_server: "{{ report_server }}"
          report_web_directory: "{{ report_web_directory }}"
          report_group: "rhel{{ ansible_distribution_version.replace('.', '_') }}"
          aap_gateway_host: "{{ lookup('ansible.builtin.env', 'CONTROLLER_HOST') }}"
          aap_workflow_template_id: "{{ lookup('ansible.controller.controller_api', 'unified_job_templates', query_params={'name': 'Linux // Patching // ' + dispatch_workflow}, expect_one=true).id }}"

    # Mostly for demo purposes; keep env clean
    - name: Delete existing schedule
      delegate_to: localhost
      ansible.controller.schedule:
        name: "Dispatcher Schedule => {{ dispatch_workflow }} on {{ inventory_hostname }}"
        unified_job_template: "Linux // Patching // {{ dispatch_workflow }}"
        state: absent

    - name: Create label
      register: r_label
      delegate_to: localhost
      ansible.controller.label:
        name: "{{ r_chg_req.record.number }}"
        organization: Autodotes
        state: present
      failed_when:
        - r_label is failed
        - r_label.msg | default('') is not search('already exists')

    - name: Create schedule
      register: r_schedule
      delegate_to: localhost
      ansible.controller.schedule:
        name: "Dispatcher Schedule => {{ dispatch_workflow }} on {{ inventory_hostname }}"
        organization: Autodotes
        labels:
          - "{{ r_chg_req.record.number }}"
        unified_job_template: "Linux // Patching // {{ dispatch_workflow }}"
        rrule: "{{ query('awx.awx.schedule_rrule', 'none', start_date=change_window_datetime, timezone=change_window_timezone) }}"
        extra_data: "{{ dispatch_host_metadata | combine(dispatch_other_data) }}"

    - name: Create job status entry
      tags: [reporting]
      delegate_to: "{{ report_server }}"
      become: true
      throttle: 1 # avoid parallel writes to same file (for better performance consider assemble)
      vars:
        link_schedule: "<a href='{{ dispatch_other_data.aap_gateway_host }}/execution/templates/workflow-job-template/{{ dispatch_other_data.aap_workflow_template_id }}/schedules/{{ r_schedule.id }}/details'>{{ r_schedule.id }}</a>"
      ansible.builtin.lineinfile:
        path: "{{ report_web_directory }}/jobs/{{ r_chg_req.record.number }}.csv"
        regexp: '^{{ inventory_hostname }},'
        line: "{{ inventory_hostname }},{{ dispatch_workflow }},{{ link_schedule }},TBD,{{ change_window_datetime }},{{ change_window_timezone }},Scheduled"
