---
- name: Generic playbook to represent workflow node
  hosts: "{{ _hosts }}"
  gather_facts: false

  vars:
    task_purpose: This is a no-op task for demo purposes
    task_output:
      action: generic
    # report_status_update: Running # Update the report
    # change_request: CHG01234 # Change request identifier
    # change_request_task: CTASK56789 # Change request task identifier

    # for reporting
    # report_server: some_host_in_inventory
    # report_web_directory: /var/www/html

  tasks:
    - name: Automation task
      ansible.builtin.debug:
        msg: "{{ task_purpose }}"

    - name: Close a change task | successful
      when: task_output.action == 'close_ctask'
      tags: snow
      delegate_to: localhost
      servicenow.itsm.change_request_task:
        number: "{{ change_request_task }}"
        state: closed
        close_code: successful
        close_notes: "Automated patching succeeded: {{ awx_job_template_name }} (id: {{ awx_job_id }})"

    - name: Update a change task | unsuccessful
      when: task_output.action == 'update_ctask'
      tags: snow
      delegate_to: localhost
      servicenow.itsm.change_request_task:
        number: "{{ change_request_task }}"
        state: closed
        close_code: unsuccessful
        close_notes: "Automated patching failed: {{ awx_job_template_name }} (id: {{ awx_job_id }})"

    - name: Update job status entry
      when:
        - report_status_update is defined
        - change_request is defined
      tags: [reporting]
      block:
        - name: Build resource links
          ansible.builtin.set_fact:
            link_schedule: "<a href='{{ aap_gateway_host }}/execution/templates/workflow-job-template/{{ aap_workflow_template_id }}/schedules/{{ awx_parent_job_schedule_id }}/details'>{{ awx_parent_job_schedule_id }}</a>"
            link_workflow: "<a href='{{ aap_gateway_host }}/execution/jobs/workflow/{{ awx_workflow_job_id }}/output'>{{ awx_workflow_job_id }}</a>"

        - name: Modify job status report
          delegate_to: "{{ report_server }}"
          become: true
          register: r_status_update
          retries: 3
          delay: "{{ 5 | random(seed=inventory_hostname) }}"
          until: r_status_update is not changed # handle potential race conditions
          ansible.builtin.lineinfile:
            path: "{{ report_web_directory }}/jobs/{{ change_request }}.csv"
            regexp: '^{{ inventory_hostname }},'
            line: "{{ inventory_hostname }},{{ report_group }},{{ link_schedule }},{{ link_workflow }},{{ change_window_datetime }},{{ change_window_timezone }},{{ report_status_update }}"

    - name: Pass data
      ansible.builtin.set_stats:
        data:
          action: "{{ task_output['action'] | default('undef') }}"
          workflow_id: "{{ awx_workflow_job_id | default('undef') }}"
          workflow_name: "{{ awx_workflow_job_name | default('undef') }}"
          job_id: "{{ awx_job_id | default('undef') }}"
          job_template_id: "{{ awx_job_template_id | default('undef') }}"
          job_template_name: "{{ awx_job_template_name | default('undef') }}"
          schedule_id: "{{ awx_parent_job_schedule_id | default('undef') }}"
          schedule_name: "{{ awx_parent_job_schedule_name | default('undef') }}"
