---
- name: Generic playbook to represent workflow node
  hosts: "{{ _hosts }}"
  gather_facts: false

  vars:
    task_purpose: This is a no-op task for demo purposes
    task_output:
      action: generic

  tasks:
    - name: Automation task
      ansible.builtin.debug:
        msg: "{{ task_purpose }}"

    - name: Pass data
      ansible.builtin.set_stats:
        data:
          action: "{{ task_output['action'] | default('undef') }}"
          workflow_id: "{{ awx_workflow_job_id | default('undef') }}"
          workflow_name: "{{ awx_workflow_job_name | default('undef') }}"
          job_id: "{{ awx_job_id | default('undef') }}"
          job_template_id: "{{ awx_job_template_id | default('undef') }}"
          job_template_name: "{{ awx_job_template_name | default('undef') }}"
          schedule_id: "{{ awx_parent_job_schedule_id | default('undef') }}"
          schedule_name: "{{ awx_parent_job_schedule_name | default('undef') }}"
