---
- name: Generic playbook to represent workflow node
  hosts: "{{ patch_targets }}"
  gather_facts: false

  vars:
    task_purpose: This is a no-op task for demo purposes
    task_output:
      action: generic

  tasks:
    - name: Automation task
      ansible.builtin.debug:
        msg: "{{ task_purpose }}"

    - name: Pass data
      ansible.builtin.set_stats:
        data: "{{ task_output }}"
